accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('edit/', views.edit, name='edit'),
    path('<int:user_pk>/follow/', views.follow, name='follow',), 
    path('<username>/', views.profile, name='profile'),
    path('profile/update_image/<int:pk>/', views.profile_image_update, name='profile_image_update'),
]

pjt/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [

    path("admin/", admin.site.urls),
    path("", include("posts.urls")),
    path("accounts/", include("accounts.urls")),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    followings = models.ManyToManyField('self', related_name='followers', symmetrical=False)
    profile_image = models.ImageField(upload_to='profile_image', blank=True, null=True)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    status_message = models.CharField(max_length=200, blank=True, null=True)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth import get_user_model, authenticate, login as django_login

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('profile_image', 'status_message')


class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control'
            }
        )
    )

    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control'
            }
        )
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = None

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')

        self.user = authenticate(
            username=username,
            password=password
        )

        if not self.user:
            raise forms.ValidationError(
                'Invalid login credentials!'
            )
        else:
            # 자기자신에 login() 메서드 추가
            setattr(self, 'login', self._login)

    def _login(self, request):
        django_login(request, self.user)


User = get_user_model()

class signupForm(forms.Form):
    username = forms.CharField(
        label='아이디',
        widget=forms.TextInput(
            attrs={'class': 'form-control'}),)
    
    password = forms.CharField(
        label='비밀번호',
        widget=forms.PasswordInput(
            attrs={'class': 'form-control'}),)
    
    email = forms.EmailField(
        label='이메일',
        widget=forms.TextInput(
            attrs={'class': 'form-control'}),)

    first_name = forms.CharField(
        label='성함',
        widget=forms.TextInput(
            attrs={'class': 'form-control'}),)

    def clean_username(self):
        data = self.cleaned_data['username']
        if User.objects.filter(username=data).exists():
            raise forms.ValidationError('Username already exists!')
        return data

accounts/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserChangeForm, LoginForm, signupForm
from django.views.decorators.http import require_POST
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model
from django.contrib.auth import get_user_model, login as django_login
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponse
from .models import User
# Create your views here.


def login(request):
    if request.user.is_authenticated:
        return redirect('posts:index')
    
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            form.login(request)
            return redirect('posts:index')
    
    else:
        form = LoginForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


@login_required
def logout(request):
    auth_logout(request)
    return redirect('accounts:login')


def signup(request):
    if request.user.is_authenticated:
        return redirect('posts:index')

    if request.method == 'POST':
        form = signupForm(request.POST, request.FILES)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            email = form.cleaned_data['email']
            first_name = form.cleaned_data['first_name']
            if User.objects.filter(username=username).exists():
                return HttpResponse(f'Username {username} is already exist')
            user = User.objects.create_user(
                username=username,
                password=password,
                email=email,
                first_name=first_name,
            )
            return redirect('accounts:login')
    else:
        form = signupForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


@login_required
def delete(request):
    request.user.delete()
    return redirect('posts:index')


@login_required
def edit(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('accounts:profile', request.user)
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/edit.html', context)


def profile(request, username):
    User = get_user_model()
    person = User.objects.get(username=username)
    posts = person.post_set.all().order_by('-created_at')
    context = {
        'person': person,
        'posts':posts,
    }
    return render(request, 'accounts/profile.html', context)


@login_required
def follow(request, user_pk):
    User = get_user_model()
    person = User.objects.get(pk=user_pk)

    if person != request.user:
        if request.user in person.followers.all():
            person.followers.remove(request.user)
            is_followed = False
        else:
            person.followers.add(request.user)
            is_followed = True
        context = {
            'is_followed': is_followed,
            'followings_count': person.followings.count(),
            'followers_count': person.followers.count(),
        }
        return JsonResponse(context)
    return redirect('accounts:profile', person.username)

@require_POST
def profile_image_update(request, pk):
    user = User.objects.get(pk=pk)
    form = CustomUserChangeForm(request.POST, request.FILES, instance=user)
    if form.is_valid():
        form.save()
        data = {'profile_image_url': user.profile_image.url}
        return JsonResponse(data)
    else:
        return JsonResponse({'error': 'Invalid form'})
    
        

accounts/templates/accounts/edit.html
{% extends 'base.html' %}
{%load static%}

{% block content %}
  <link rel="stylesheet" href="{% static 'css/edit.css' %}">
  <div class="header">
    <h1>설정</h1>
  </div>

  <div class="container box1">
    <h2>Edit profile</h2>

    <!-- profile image -->
    <form action="{%url 'accounts:edit'%}" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="d-flex profile_1">
        {%if user.profile_image %}
          <img src="{{ user.profile_image.url }}" alt="post_image" class="col-3" style="width: 110px; border-radius: 100%;" >
        {% else %}
          <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLIbLTGKz4waJGU2vkbhQkRavjf2OdeY7Eo4l8yFnggdF3fX1bUF4FEUP13o34ioSCm-M&usqp=CAU" alt="no_image" class="col-3" style="width: 110px; object-fit: cover;">
        {% endif %}
        <!-- ID -->
        <div class="form-group sub_1">
          <h2>
            {{ user.username }}
          </h2>
          <!-- 사진등록 Input -->
          <input type="file" class="form-control" name="profile_image" id="profile_image">
        </div>
      </div>

      <div class=" sub_2">
        <!-- 웹사이트 -->
        <div class="sub2-2" style="text-align:center">
          <label>웹사이트</label>
          <input type="text" placeholder="웹사이트" disabled="disabled">
        </div>

        <div>
          <!-- 웹사이트 메시지 -->
          <p>링크 수정은 모바일에서만 가능합니다. Instagram 앱으로 이동하여 프로필의 소개에서 웹사이트를 변경하여 수정하세요.</p>
        </div>

      </div>

      <!-- 소개 -->
      <div class="sub">
        <label>소개</label>
        <textarea class="comment_1" name="status_message" id="status_message" cols="30" rows="10">{{ user.status_message }}</textarea>
      </div>

      <!-- 버튼 -->
      <div class="button_settings">
        <input type="submit" class="btn btn-primary" value="Submit">
        <a href="{% url 'accounts:delete' %}" class="btn btn-danger">회원탈퇴</a>
      </div>
    </form>
  {% endblock content %}

accounts/templates/accounts/login.html
<!doctype html>
<html lang="en">

  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>login.html</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <!--css적용링크 -->
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <!-- 글꼴 -->
  </head>

  <body>
    <div class="container">

      <div class="login_form">
        <!-- 로그인 폼 -->
        <img class="main_img" src="{% static 'img/main_img1.png' %}" alt="메인 이미지">
        <form action="{% url 'accounts:login' %}" method="POST">
          {% csrf_token %}
          <input type="text" placeholder="사용자 이름" class="input_size form-control" name="username">
          <br>
          <input type="password" placeholder="비밀번호" class="input_size form-control" name='password'>
          <br>
          <input class="btn btn-primary login_button" type="submit" value="로그인"></input>
        </form>

      </div>

      <!-- 회원가입 링크 연결 -->
      <div class="haveAccount">
        <p>계정이 없으신가요?
          <a href="{% url 'accounts:signup' %}" class="noneunderline">가입하기</a>
        </p>
      </div>

      <br>
      <!-- 앱 링크 인스타그램 -->
      <div>
        <p>앱을 다운로드하세요.</p>
      </div>
      <br>
      <div>
        <a href="https://apps.apple.com/app/instagram/id389801252?vt=lo">
          <img class="down_img" src="https://static.cdninstagram.com/rsrc.php/v3/yi/r/cWx_hQBPmbo.png" alt=""></a>
        <a href="https://play.google.com/store/apps/details?id=com.instagram.android&referrer=utm_source%3Dinstagramweb%26utm_campaign%3DloginPage%26ig_mid%3DCE0AAB29-A2D1-4154-B258-8846EA93110B%26utm_content%3Dlo%26utm_medium%3Dbadge&pli=1">
          <img class="down_img" src="https://static.cdninstagram.com/rsrc.php/v3/ye/r/UtJtFmFLCiD.png" alt=""></a>
      </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </body>

</html>

accounts/templates/accounts/signup.html
<!doctype html>
<html lang="en">

  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>join page</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <!--css적용링크 -->
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/join.css' %}">
  </head>

  <body>
    <div class="container">
      <div class="login_form">
        <!-- 로그인 폼 -->
        <img class="main_img" src="{% static 'img/main_img1.png' %}" alt="메인 이미지">
        <h2 class="join_font_size mb-5">친구들의 사진과 동영상을 보려면 가입하세요.</h2>
        <form action="{% url 'accounts:signup' %}" method="POST">
          {% csrf_token %}

          <!-- 입력 폼 -->
          <input type="text" placeholder="이메일 주소" class="input_size form-control" name="email">
          <input type="text" placeholder="성명" class="input_size form-control" name='first_name'>
          <input type="text" placeholder="사용자 이름" class="input_size form-control" name="username">
          <input type="password" placeholder="비밀번호" class="input_size form-control" name="password">
          <input class="btn btn-primary join_button" type="submit" value="가입"></input>
        </form>
      </div>

      <!-- 회원가입 링크 연결 -->
      <div class="haveAccount">
        <p>계정이 있으신가요?
          <a href="{% url 'accounts:login'%}" class="noneunderline">로그인</a>
        </p>
      </div>

      <!-- 앱 다운로드 -->
      <div>
        <p class="app_font">앱을 다운로드하세요.</p>
        <a href="https://apps.apple.com/app/instagram/id389801252?vt=lo">
          <img class="down_img" src="https://static.cdninstagram.com/rsrc.php/v3/yi/r/cWx_hQBPmbo.png" alt=""></a>
        <a href="https://play.google.com/store/apps/details?id=com.instagram.android&referrer=utm_source%3Dinstagramweb%26utm_campaign%3DloginPage%26ig_mid%3DCE0AAB29-A2D1-4154-B258-8846EA93110B%26utm_content%3Dlo%26utm_medium%3Dbadge&pli=1">
          <img class="down_img" src="https://static.cdninstagram.com/rsrc.php/v3/ye/r/UtJtFmFLCiD.png" alt=""></a>
      </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </body>

</html>